package com.cvele.ws.order;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-20T10:17:44.402+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://www.cvele.com/ws/Order/", name = "Order")
@XmlSeeAlso({ObjectFactory.class, com.cvele.ws.order.entities.ObjectFactory.class})
@HandlerChain(file = "classpath:handlerConfig.xml")
public interface Order {

    @WebMethod
    @RequestWrapper(localName = "getPizzaById", targetNamespace = "http://www.cvele.com/ws/Order/", className = "com.cvele.ws.order.GetPizzaById")
    @ResponseWrapper(localName = "getPizzaByIdResponse", targetNamespace = "http://www.cvele.com/ws/Order/", className = "com.cvele.ws.order.GetPizzaByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.cvele.ws.order.entities.Pizza getPizzaById(
        @WebParam(name = "id", targetNamespace = "")
        int id
    );
}
