
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cvele.ws.order;

import com.cvele.ws.order.entities.Pizza;
import java.math.BigDecimal;
import javax.annotation.Resource;
import javax.xml.ws.WebServiceContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.stereotype.Component;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-20T10:17:44.333+02:00
 * Generated source version: 3.2.0
 * 
 */
@Component
@javax.jws.WebService(
                      serviceName = "Order",
                      portName = "OrderService",
                      targetNamespace = "http://www.cvele.com/ws/Order/",
                      wsdlLocation = "file:/C:/Users/nikolac/Documents/NetBeansProjects/JavaApplication5/SoapWS/src/main/config/soap.wsdl",
                      endpointInterface = "com.cvele.ws.order.Order")
                      
public class OrderServiceImpl implements Order {

    private static final Logger LOG = LogManager.getLogger(OrderServiceImpl.class);
    
    @Resource
    WebServiceContext context;

    /* (non-Javadoc)
     * @see com.cvele.ws.order.Order#getPizzaById(int id)*
     */
    @Override
    public com.cvele.ws.order.entities.Pizza getPizzaById(int id) { 
        LOG.info("Executing operation getPizzaById");
        Pizza p = new Pizza();
        p.setId(1);
        p.setName("Capriciosa");
        p.setPrice(BigDecimal.valueOf(156.45));
        System.out.println(context);
        return p;
    }

}
