
package com.cvele.ws.order;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-20T10:17:44.414+02:00
 * Generated source version: 3.2.0
 * 
 */
 
public class Order_OrderService_Server{

    protected Order_OrderService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OrderServiceImpl();
        String address = "http://www.cvele.com/ws/Order/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Order_OrderService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
