package com.cvele.ws.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-20T10:17:44.423+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "Order", 
                  wsdlLocation = "file:/C:/Users/nikolac/Documents/NetBeansProjects/JavaApplication5/SoapWS/src/main/config/soap.wsdl",
                  targetNamespace = "http://www.cvele.com/ws/Order/") 
public class Order_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cvele.com/ws/Order/", "Order");
    public final static QName OrderService = new QName("http://www.cvele.com/ws/Order/", "OrderService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/nikolac/Documents/NetBeansProjects/JavaApplication5/SoapWS/src/main/config/soap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Order_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/nikolac/Documents/NetBeansProjects/JavaApplication5/SoapWS/src/main/config/soap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Order_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Order_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Order_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Order_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Order_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Order_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Order
     */
    @WebEndpoint(name = "OrderService")
    public Order getOrderService() {
        return super.getPort(OrderService, Order.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Order
     */
    @WebEndpoint(name = "OrderService")
    public Order getOrderService(WebServiceFeature... features) {
        return super.getPort(OrderService, Order.class, features);
    }

}
